package transfer

const (
	EVENT_CLIENT_CONNECTED    = "EVENT_CLIENT_CONNECTED"
	EVENT_CLIENT_DISCONNECTED = "EVENT_CLIENT_DISCONNECTED"

	EVENT_SERVER_STARTED    = "EVENT_SERVER_STARTED"
	EVENT_SERVER_ERROR      = "EVENT_SERVER_ERROR"
	EVENT_SERVER_STOPPED    = "EVENT_SERVER_STOPPED"
	EVENT_SERVER_NEW_CLIENT = "EVENT_SERVER_NEW_CLIENT"
)
