package transfer

const (
	EVENT_CLIENT_DISCONNECTED string = "EVENT_CLIENT_DISCONNECTED" /* func(transfer.IClient) */
	EVENT_SERVER_STARTED      string = "EVENT_SERVER_STARTED"
	EVENT_SERVER_ERROR        string = "EVENT_SERVER_ERROR"
	EVENT_SERVER_STOPPED      string = "EVENT_SERVER_STOPPED"
	EVENT_SERVER_NEW_CLIENT   string = "EVENT_SERVER_NEW_CLIENT"
)
