// Code generated by "stringer -type=PackageType"; DO NOT EDIT.

package pkg

import "fmt"

const (
	_PackageType_name_0 = "PKG_NOTIFYPKG_REQUESTPKG_RESPONSEPKG_PUSHPKG_HEARTBEATPKG_HEARTBEAT_RESPONSEPKG_HAND_SHAKEPKG_HAND_SHAKE_RESPONSE"
	_PackageType_name_1 = "PKG_RPC_NOTIFYPKG_RPC_REQUESTPKG_RPC_RESPONSEPKG_RPC_PUSH"
	_PackageType_name_2 = "PKG_RPC_BROADCAST"
)

var (
	_PackageType_index_0 = [...]uint8{0, 10, 21, 33, 41, 54, 76, 90, 113}
	_PackageType_index_1 = [...]uint8{0, 14, 29, 45, 57}
	_PackageType_index_2 = [...]uint8{0, 17}
)

func (i PackageType) String() string {
	switch {
	case 0 <= i && i <= 7:
		return _PackageType_name_0[_PackageType_index_0[i]:_PackageType_index_0[i+1]]
	case 16 <= i && i <= 19:
		i -= 16
		return _PackageType_name_1[_PackageType_index_1[i]:_PackageType_index_1[i+1]]
	case i == 24:
		return _PackageType_name_2
	default:
		return fmt.Sprintf("PackageType(%d)", i)
	}
}
