// Code generated by "stringer -type=RouteIndex"; DO NOT EDIT.

package pkg

import "fmt"

const _RouteIndex_name = "ROUTE_INDEX_NONE"

var _RouteIndex_index = [...]uint8{0, 16}

func (i RouteIndex) String() string {
	if i >= RouteIndex(len(_RouteIndex_index)-1) {
		return fmt.Sprintf("RouteIndex(%d)", i)
	}
	return _RouteIndex_name[_RouteIndex_index[i]:_RouteIndex_index[i+1]]
}
